import type { Environment } from "./environment";

export type Action = {
  // "id" field is a unique identifier for each action.
  // this field will be automatically generated by mrdamian core,
  // so users don't need to specify this field.
  id: string;
  // "type" field is a component type.
  type: string;
  // "action" field is a action type.
  // Each action type has different behavior.
  // if user didn't specify this field, mrdamian core will fill this variable as ""(empty string) action.
  // In normal case, for such default action type,
  // you should proivde default behavior and initialization for the component instance.
  action: string;
  // "name" field is a unique identifier for component instance.
  // this name will be used for assigning result to environment.
  // for example, if a component specified type = "twitch", name = "main",
  // the result value of the component will be assigned to "twitch.main".
  // it means, { "twitch": { "main": ... } } will be merged into current environment.
  name?: string;
  // "when" field is an expression for conditional execution.
  // this expression don't need define with "$" prefix.
  when?: string;
  // "args" field is a list of arguments for component.
  args?: Environment;
};
